M48
; DRILL file {KiCad 7.0.1} date Wed Mar 29 13:12:43 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-03-29T13:12:43+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C2.200
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X80.0Y-31.0
X100.0Y-31.0
T2
X86.1Y-22.2
X93.9Y-22.2
T0
M30
